set keymap=dvorak


fun! ToggleKeymap()
	if &keymap!='dvorak'
		echo "Turning dvorak ON"
		set keymap=dvorak
	else
		echo "Turning dvorak OFF"
		set keymap=
	endif
endfun
nnoremap ,d :call ToggleKeymap()<CR>

nmap <C-t> :tabnew<CR>
