# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"
export HISTCONTROL=erasedups
export HISTSIZE=5000
# shopt -s histappend  # append to bash_history if Terminal.app quits
export USE_LIBPCRE=yes
setopt extendedglob
# export LESSOPEN="| src-hilite-lesspipe.sh %s"
# export LESS=" -R "
disable r


# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions pip python tmux sublime cp autopep8)


source $ZSH/oh-my-zsh.sh

# might need to specify local brew location
source ~/.config/local.sh
BREW=$(brew --prefix)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
#   export GIT_EDITOR='vim'
# else
#   export EDITOR='nvim'
#   export GIT_EDITOR='nvim'
# fi

if ! type "$nvim" > /dev/null; then
  export EDITOR='nvim'
  export GIT_EDITOR='nvim'
else
  export EDITOR='vim'
  export GIT_EDITOR='vim'
fi

# Load after plugins (gc alias conflict)
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Python
export PYTHONDONTWRITEBYTECODE=True


# Aliases
agpy () {
  ag "$@" **/*.py
}

ptpy () {
  pt --file-search-regexp=".+?\.py$" --depth=3 "$@"
}


fpath=($BREW/share/zsh-completions $fpath)

# autojump/autoenv
[ -f $BREW/etc/profile.d/autojump.sh ] && . $BREW/etc/profile.d/autojump.sh
#source $BREW/opt/autoenv/activate.sh
export HOMEBREW_CASK_OPTS="--appdir=/Applications --fontdir=/Library/Fonts"




# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/wbeard/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/wbeard/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/wbeard/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/wbeard/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

